### ISSUE TITLE
使用weixinalarm时出现corpid未定义

### ISSUE THREAD

**Issue by wp861010** [yxxhero/weixinalarm#1]
from weixinalarm import weixinalarm
sender=weixinalarm(corpid=wxa35b4146efb500ca,secrect=ll8ONe1w2uwB_KzqlWoEEm6olUXLGirplQNjdCvRQRI,agentid=1000024)
sender.sendmsg(title="自定义",description="自定义")

File "c:\Users\wangpeng\Desktop\企业微信py\sendmess.py", line 2, in <module>
    sender=weixinalarm(corpid=wxa35b4146efb500ca,secrect=ll8ONe1w2uwB_KzqlWoEEm6olUXLGirplQNjdCvRQRI,agentid=1000024)
NameError: name 'wxa35b4146efb500ca' is not defined

**Comment by yxxhero** [comment]
```
sender=weixinalarm(corpid="wxa35b4146efb500ca",secrect="ll8ONe1w2uwB_KzqlWoEEm6olUXLGirplQNjdCvRQRI",agentid=1000024)
```

请注意敏感信息泄露  另外这个库比较旧了 建议参考最近的微信文档来调用  @wp861010
